function [fitresult, gof] = createFit(sn, bestK)
%CREATEFIT(SN,BESTK)
%  Create a fit.
%
%  Data for 'kModel' fit:
%      X Input : sn
%      Y Output: bestK
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Nov-2018 03:29:55


%% Fit: 'kModel'.
[xData, yData] = prepareCurveData( sn, bestK );

% Set up fittype and options.
ft = fittype( 'poly4' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'kModel' );
h = plot( fitresult, xData, yData );
legend( h, 'bestK vs. sn', 'kModel', 'Location', 'NorthEast' );
% Label axes
xlabel sn
ylabel bestK
grid on


